### PR TITLE
[BRAN-204] Transparency Colors

### PR DESCRIPTION
**Pull request by Alderr**
## Purpose/Description:

- Added new util function to create transparency colors for the dashboard

## Jira Link: 

[BRAN-204](https://collagegroup.atlassian.net/browse/BRAN-204)

[BRAN-204]: https://collagegroup.atlassian.net/browse/BRAN-204?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

### CODE REVIEW

**Review by TrevorCollins — APPROVED** [review]

**Review by jeffarrubla — APPROVED** [review]
nice!

**Comment by jeffarrubla** [comment]
@Alderr should we add in storybook info about this function as we have done with other button, typography, ect?

image

**Comment by jeffarrubla** [comment]
Here in the example usage

image

it'd be nice the outputs will be the the same as in the swatches

**Review by jeffarrubla — APPROVED** [review]
Great work!

**Pull request merged**
